MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
EXTRAKEY_ENABLE = yes # controls volume
TAP_DANCE_ENABLE = no
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
